name: Run Colab Notebook

on:
  schedule:
    - cron: '0 */6 * * *' # Runs every 6 hours
  workflow_dispatch: # Allow manual triggering

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up Python environment
    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # Install dependencies
    - name: Install dependencies
      run: |
        pip install jupyter ipykernel
        pip install papermill[github]

    # Run the Colab notebook
    - name: Run the Colab notebook
      run: |
        python run_test_notebook.py

    # Upload executed notebook as an artifact (optional)
    - name: Upload executed notebook
      uses: actions/upload-artifact@v3
      with:
        name: executed-notebook
        path: /tmp/test_output_notebook.ipynb

    # Commit and push the executed notebook to the repository
    - name: Commit and push updated notebook
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        cp /tmp/test_output_notebook.ipynb ./test_output_notebook.ipynb
        git add ./test_output_notebook.ipynb
        git commit -m "Update executed notebook [skip ci]"
        git push origin main
